### ISSUE TITLE
Error while executing the file Automatic_Bangla_Number_Plate_Recognition_EasyOCR.ipynb

### ISSUE THREAD

**Issue by akbarhussain7** [FardinHash/EasyOCR-based-Automatic-Bangla-License-Plate-Recognition#1]
While trying to replicate this file, I have realized that no variable with the name "img" has been declared in the program. This has resulted in an error while executing the program. 

![image](https://user-images.githubusercontent.com/74524892/231348992-04b246bc-d757-45ae-9814-433fcd1351e1.png)

It will be really helpful if you could suggest a way to overcome this error. Thank you

**Comment by FardinHash** [comment]
@akbarhussain7 before executing this cell, did you load the image file?
